"""v2

Revision ID: 0753f7037c90
Revises: f594c81cf4b7
Create Date: 2022-01-16 17:22:50.062479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0753f7037c90'
down_revision = 'f594c81cf4b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_matches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guid', postgresql.UUID(), nullable=True),
    sa.Column('id_opposing_team', sa.BigInteger(), nullable=True),
    sa.Column('id_home_team', sa.BigInteger(), nullable=True),
    sa.Column('id_cup', sa.BigInteger(), nullable=True),
    sa.Column('total_goals', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('time_additions', sa.Integer(), nullable=True),
    sa.Column('total_time_pause', sa.Integer(), nullable=True),
    sa.Column('final_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cup'], ['tb_cups.id'], ),
    sa.ForeignKeyConstraint(['id_home_team'], ['tb_teams.id'], ),
    sa.ForeignKeyConstraint(['id_opposing_team'], ['tb_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_matches_guid'), 'tb_matches', ['guid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_matches_guid'), table_name='tb_matches')
    op.drop_table('tb_matches')
    # ### end Alembic commands ###
