"""v14

Revision ID: 35e0f0e8affd
Revises: 78a7788c15d1
Create Date: 2022-06-22 21:33:45.034985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35e0f0e8affd'
down_revision = '78a7788c15d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_purchases',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guid', postgresql.UUID(), nullable=True),
    sa.Column('id_user', sa.BigInteger(), nullable=True),
    sa.Column('date_purchase', sa.DateTime(), nullable=True),
    sa.Column('date_expired_purchase', sa.DateTime(), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('price_br', sa.Float(), nullable=True),
    sa.Column('platform', sa.Enum('ANDROID', 'IOS', name='platformenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['tb_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_purchases_guid'), 'tb_purchases', ['guid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_purchases_guid'), table_name='tb_purchases')
    op.drop_table('tb_purchases')
    # ### end Alembic commands ###
