"""v1

Revision ID: 3a5a6b3c2ee3
Revises: 
Create Date: 2021-12-19 00:24:16.923499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a5a6b3c2ee3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_goals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guid', postgresql.UUID(), nullable=True),
    sa.Column('player', sa.String(), nullable=True),
    sa.Column('time_goals', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_goals_guid'), 'tb_goals', ['guid'], unique=False)
    op.create_table('tb_skills',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guid', postgresql.UUID(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('velocity', sa.Integer(), nullable=True),
    sa.Column('completion', sa.Integer(), nullable=True),
    sa.Column('dribble', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_skills_guid'), 'tb_skills', ['guid'], unique=False)
    op.create_table('tb_sports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guid', postgresql.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('tutorial', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_sports_guid'), 'tb_sports', ['guid'], unique=False)
    op.create_table('tb_teams',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guid', postgresql.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('victories', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('goals_negative', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_teams_guid'), 'tb_teams', ['guid'], unique=False)
    op.create_table('tb_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guid', postgresql.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_access', sa.Boolean(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'FREE', 'PREMIUM', name='rolesenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_users_guid'), 'tb_users', ['guid'], unique=False)
    op.create_table('tb_cups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guid', postgresql.UUID(), nullable=True),
    sa.Column('id_team', sa.BigInteger(), nullable=True),
    sa.Column('responsible_email', sa.String(), nullable=True),
    sa.Column('id_sport', sa.BigInteger(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('time_additions', sa.Integer(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_sport'], ['tb_sports.id'], ),
    sa.ForeignKeyConstraint(['id_team'], ['tb_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_cups_guid'), 'tb_cups', ['guid'], unique=False)
    op.create_table('tb_positions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guid', postgresql.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id_sport', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_sport'], ['tb_sports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_positions_guid'), 'tb_positions', ['guid'], unique=False)
    op.create_table('tb_players',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guid', postgresql.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id_position', sa.BigInteger(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('id_skill', sa.BigInteger(), nullable=True),
    sa.Column('user_responsible', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_position'], ['tb_positions.id'], ),
    sa.ForeignKeyConstraint(['id_skill'], ['tb_skills.id'], ),
    sa.ForeignKeyConstraint(['user_responsible'], ['tb_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_players_guid'), 'tb_players', ['guid'], unique=False)
    op.create_table('tb_relation_cups_teams',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guid', postgresql.UUID(), nullable=True),
    sa.Column('cup_id', sa.BigInteger(), nullable=True),
    sa.Column('team_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cup_id'], ['tb_cups.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['tb_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_relation_cups_teams_guid'), 'tb_relation_cups_teams', ['guid'], unique=False)
    op.create_table('tb_relation_teams_players',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guid', postgresql.UUID(), nullable=True),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('team_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['tb_players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['tb_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_relation_teams_players_guid'), 'tb_relation_teams_players', ['guid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_relation_teams_players_guid'), table_name='tb_relation_teams_players')
    op.drop_table('tb_relation_teams_players')
    op.drop_index(op.f('ix_tb_relation_cups_teams_guid'), table_name='tb_relation_cups_teams')
    op.drop_table('tb_relation_cups_teams')
    op.drop_index(op.f('ix_tb_players_guid'), table_name='tb_players')
    op.drop_table('tb_players')
    op.drop_index(op.f('ix_tb_positions_guid'), table_name='tb_positions')
    op.drop_table('tb_positions')
    op.drop_index(op.f('ix_tb_cups_guid'), table_name='tb_cups')
    op.drop_table('tb_cups')
    op.drop_index(op.f('ix_tb_users_guid'), table_name='tb_users')
    op.drop_table('tb_users')
    op.drop_index(op.f('ix_tb_teams_guid'), table_name='tb_teams')
    op.drop_table('tb_teams')
    op.drop_index(op.f('ix_tb_sports_guid'), table_name='tb_sports')
    op.drop_table('tb_sports')
    op.drop_index(op.f('ix_tb_skills_guid'), table_name='tb_skills')
    op.drop_table('tb_skills')
    op.drop_index(op.f('ix_tb_goals_guid'), table_name='tb_goals')
    op.drop_table('tb_goals')
    # ### end Alembic commands ###
