"""v13

Revision ID: 78a7788c15d1
Revises: f35bb4a9abe7
Create Date: 2022-06-12 16:30:28.784091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a7788c15d1'
down_revision = 'f35bb4a9abe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_notifications', sa.Column('is_read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_notifications', 'is_read')
    # ### end Alembic commands ###
