"""v2

Revision ID: d34453479fcd
Revises: 0753f7037c90
Create Date: 2022-01-16 18:53:55.131409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd34453479fcd'
down_revision = '0753f7037c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_goals', sa.Column('id_player', sa.BigInteger(), nullable=True))
    op.add_column('tb_goals', sa.Column('id_match', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'tb_goals', 'tb_players', ['id_player'], ['id'])
    op.create_foreign_key(None, 'tb_goals', 'tb_players', ['id_match'], ['id'])
    op.drop_column('tb_goals', 'player')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_goals', sa.Column('player', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tb_goals', type_='foreignkey')
    op.drop_constraint(None, 'tb_goals', type_='foreignkey')
    op.drop_column('tb_goals', 'id_match')
    op.drop_column('tb_goals', 'id_player')
    # ### end Alembic commands ###
